### ISSUE TITLE
CNVnator genotype

### ISSUE THREAD

**Issue by xiachujing** [abyzovlab/CNVnator#36] opened 2016-08-20 15:51 UTC
I used the following commands to get genotypes,

./cnvnator   -root sample.root -genome hg19 -chrom chr1 -unique -tree chr1.bam
./cnvnator   -root sample.root -genome hg19 -chrom chr1 -d ./b37 -his 100
./cnvnator   -root sample.root -chrom chr1 -stat 100
./cnvnator   -root sample.root  -chrom chr1 -partition 100
./cnvnator   -root sample.root -d ./b37 -genotype 100

For the step5, when appeared ">", I typed "chr1:1-1000", then the output is 
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype chr1:1-1000 sample.root -1 -1

Why the copy number of my data is "-1" . I tried lots of data, all outputs are the same.
I can use the sample.root to call CNV sucessfully.

Thanks.

**Comment by abyzov** [comment] 2016-08-23 03:25
Hi,
please let me know whether you are getting the same output for other region, e.g., one of the CNVnator calls.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by TracyBallinger** [comment] 2016-11-07 14:50
Hello, I have also gotten the same error.  I have the cnv.calls and I do this command: 
awk '{print $2}END{print "exit"}' cnv.calls | $cnvnatordir/cnvnator -root out.root -genotype 100

The output is all -1: 
Genotype chr1:1-10000 out.root 0 -1
Genotype chr1:11401-40000 out.root 4.67967 -1
Genotype chr1:40001-50600 out.root 0.786928 -1
Genotype chr1:52701-60500 out.root 0.627684 -1

This is there error message that is posted.  
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.

**Comment by abyzov** [comment] 2016-11-07 17:11
Hi,
the second value of genotype is calculated for bins of 1000 bps. If you haven’t precalculated statistics for such bins the program will through a warning and print -1 (the last field).

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by JohnMCMa** [comment] 2017-09-27 14:42
I have the same issue. If I used `-genotype 100` on a root file that has been consistently been using 100bp bins, then why should the program need to complain about the lack of 1000bp bins anyway?

**Comment by abyzov** [comment] 2017-10-17 04:36
Genotyping with 1000 bp bins is currently hardcoded. So, the software will always attempt genotyping with the bin size you provided and for 1000 bp bins. That is why there are two value at the end of genotyping line.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by 54tuifeimo** [comment] 2017-11-16 10:59
I did the -genotype for one sample, and got the similar result.  Why there are so many "Can't find directory 'bin_1000'." in the result? 

And I find the value in genotype after A14002.root(like 1.1111; 1.04039) is just twice as large as the normalized_RD value in the call results. So, what is the purpose do the genotype step? Thanks!

Command:
awk '{ print $2 } END { print "exit" }' A14002_call.txt | ./cnvnator -root A14002.root -genotype 300

Genotype Results:
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:480901-485100 A14002.root 1.1111 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:3118801-3122700 A14002.root 1.04039 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:3166801-3169200 A14002.root 0.593313 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:3220201-3221400 A14002.root 0.346574 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:3719401-3720900 A14002.root 0.216988 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:4760101-4765500 A14002.root 1.13509 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:4875901-4877400 A14002.root 1.19764 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:4877401-4882800 A14002.root 1.1265 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:5409001-5417100 A14002.root 1.0804 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:6138901-6142800 A14002.root 1.02279 -1
Can't find directory 'bin_1000'.
Can't find directory 'bin_1000'.
Genotype 1:7206601-7207500 A14002.root 0.443192 -1

Call results:
deletion	1:480901-485100	4200	0.55564	0.00761255	0.150203	2.57981	1.19544	0.0125
deletion	1:3118801-3122700	3900	0.520294	0.0054756	0.0121636	126.188	2158.37	0
deletion	1:3166801-3169200	2400	0.296928	4.01186	0.0278923	209208	43300.8	0.41784
deletion	1:3220201-3221400	1200	0.173391	524.593	2.09039e-05	1	1	0.835821
deletion	1:3719401-3720900	1500	0.108626	106.246	3.21491e-08	1	1	0.0392157
deletion	1:4760101-4765500	5400	0.567636	1.00762e-05	3.96744e-06	0.0297054	0.356192	0
deletion	1:4875901-4877400	1500	0.599211	198.3	11076.1	1	1	0
duplication	1:4877401-4882800	5400	0.563324	0.0427723	22965.7	0.888057	315.077	0.00863558
deletion	1:5409001-5417100	8100	0.540279	1.09892e-06	1.32257e+08	7.52378e-05	2.62086e+08	0.0480296
deletion	1:6138901-6142800	3900	0.511491	0.000647497	3.56678e-08	5.23082	2.2643	0.0200445
deletion	1:7206601-7207500	900	0.221903	1726.91	0.0127266	1	1	0.00917431
duplication	1:7326601-7330200	3600	2.04106	0.0024892	1.56952e-24	21.6081	4.29977e-16	0.000645578

**Comment by abyzov** [comment] 2017-11-28 06:43
CNVnator produces genotype with provide bin size and with bins of 1000 bp. The latter is hardcoded. If you don’t generate histograms for bins of 1000 bp, the software prints an error message.
One can use genotype to genotype CNVs in samples other then the sample where CNV was discovered.
For the sample where CNV was discovered genotype is the double of normalized RD for diploid chromosomes and is equal to normalized RD for haploid chromosome.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by osowiecki** [comment] 2019-07-19 02:53
I have CNVNATOR confirmed calls in result file (vcf below) :

10      21901   CNVnator_dup_1  N       <DUP>   .       PASS    END=25600;SVTYPE=DUP;SVLEN=3700;IMPRECISE;natorRD=2.51183;natorP1=7.8463e-07;natorP2=2.01362e-10;natorP3=0.000776324;natorP4=3.0325e-35;natorQ0=0.211345        GT:CN   ./1:3                                


When I check the genotype of that region :

sudo docker exec -i CF_6916 cnvnator -root /data/CF_6916.root -d /data/genome -genotype 100 << EOF
10:21901-25600
exit
EOF

Error in <TString::AssertElement>: out of bounds: i = -1, Length = 0
Genotype 10:21901-25600 /data/CF_6916.root 5.02275 -1

I get -1 in every case. 
Can you confim if this works correctly in the latest build of CNVnator?

**Comment by abyzov** [comment] 2019-08-08 18:59
Hi,
yes it works correct. The warning message is now fixed in GitHub.
-1 is a genotype with 1000 bins. Looks like you don’t have histograms of such bin size in you root so the value is -1.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Closed** 2021-04-22 19:47 UTC
