### ISSUE TITLE
Histogram error

### ISSUE THREAD

**Issue by Madelinehazel** [abyzovlab/CNVnator#18] opened 2016-02-10 19:33 UTC
Hello,

When I try to generate a histogram ($./cnvnator -root out.root -his 100) I get the following message, for all contigs:

Calculating histograms with bin size of 100 for 'GL000192.1' ...
Making GC histogram for 'GL000192.1' ...
Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (547496) for 'GL000192.1'.
Doing nothing!

I'm not sure what the problem is. My input is .bam files. Your help would be appreciated!

Thanks, 
Madeline

**Comment by abyzov** [comment] 2016-02-10 23:42
Hello,
looks like the problem is in file for conting GL000192.1 not being found.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Madelinehazel** [comment] 2016-02-11 00:33
Would the issue then be with my chr*.fa files?

**Comment by abyzov** [comment] 2016-02-29 07:23
Yes, I believe so.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ggg3** [comment] 2016-04-07 15:19
Hi Madeline,
I am getting the same error and was wondering how did you fix this issue ?

**Comment by srmcgee** [comment] 2016-07-18 20:30
Hello Alexej,
I am having a similar problem with CNVnator 0.2.7 when I try to create histograms from the grc38 fasta (hs38DH) with the following command:

cnvnator -genome hs38DH -root [sample].root -his 100 -d [chromDir].

This stops creating histograms at chromosome 5.  

What I have noticed is that the info line on the chr5.fa file has an extra entry (hm:…) 
>5  AC:CM000667.2  gi:568336019  LN:181538259  rl:Chromosome  M5:a811b3dc9fe66af729dc0dddf7fa4f13  AS:GRCh38  hm:47309185-49591369

(Chromosomes 1-4 do not
>4  AC:CM000666.2  gi:568336020  LN:190214555  rl:Chromosome  M5:3210fecf1eb92d5489da4346b3fddc6e  AS:GRCh38)

If I manually edit this line to remove the "hm" field, cnvnator creates the histogram for chr5 but then fails again on the very next chromosome with an "hm" field (chrY).

Is this issue perhaps fixed in the latest version of cnvnator (0.3.2)?

Thank you for the help.
Sean

**Comment by abyzov** [comment] 2016-07-21 03:12
Hi,
there were issues in the initial CNVnator code with parsing chromosome. Later the issues were fixed.
Description line is ignored by CNVnator, as it assume the files has only one chromosome defined by file name. Please try the latest version.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Closed** 2021-04-22 19:45 UTC
